apiVersion: v1
kind: Namespace
metadata:
  name: shiba
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shiba
  namespace: shiba
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shiba
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ "kubeadm-config" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shiba
subjects:
  - kind: ServiceAccount
    name: shiba
    namespace: shiba
roleRef:
  kind: ClusterRole
  name: shiba
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: shiba
  namespace: shiba
  labels:
    app: shiba
spec:
  selector:
    matchLabels:
      app: shiba
  template:
    metadata:
      labels:
        app: shiba
    spec:
      volumes:
        - name: cni-config
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
        - name: tmp
          hostPath:
            path: /tmp/shiba
            type: DirectoryOrCreate
      containers:
        - name: shiba
          image: moycat/shiba:latest
          env:
            - name: SHIBA_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: SHIBA_APITIMEOUT
              value: "30"
            - name: SHIBA_CNICONFIGPATH
              value: "/etc/cni/net.d"
#            - name: SHIBA_CLUSTERPODCIDRS
#              value: "192.168.0.0/16,fddd:dead:beef::/48"
#            - name: SHIBA_IP6TNLMTU
#              value: "1500"
#            - name: SHIBA_PPROFPORT
#              value: "7442"
#            - name: SHIBA_DEBUG
#              value: "true"
          volumeMounts:
            - name: cni-config
              mountPath: /etc/cni/net.d
            - name: tmp
              mountPath: /tmp
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      serviceAccountName: shiba
      tolerations:
        - operator: Exists
