name: Publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
      latest:
        description: 'Push latest'
        required: false
        type: boolean
        default: true
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      IMAGE_TAGS: moycat/shiba:${{ github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: moycat
          password: ${{ secrets.DOCKER_TOKEN }}
      - if: ${{ github.event.inputs.latest == 'true' }}
        run: echo "IMAGE_TAGS=$IMAGE_TAGS,moycat/shiba:latest" >> $GITHUB_ENV
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_TAGS }}
          push: ${{ github.event.inputs.dry-run != 'true' }}
